SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Transfer_History;
DROP TABLE IF EXISTS Scouting_Report;
DROP TABLE IF EXISTS Att_Stats;
DROP TABLE IF EXISTS S_Stats;
DROP TABLE IF EXISTS L_Stats;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Player_Position;
DROP TABLE IF EXISTS Game;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Team;

SET FOREIGN_KEY_CHECKS = 1;